import type { Metadata } from "next";
import "../../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <body className="min-h-screen flex flex-col">
       
            <main className="flex justify-center items-start flex-grow">
              {/* Sayfa içeriğini buraya yerleştirebilirsiniz */}
              <div className="flex justify-start items-start mx-4">
                {children}
              </div>
            </main>
  
        </body>
      </html>
    )
}
